Check coding style in CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,6 +1,29 @@
 name: my_FTP CI
 on: [push]
 jobs:
+  coding-style:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+      - name: Get banana script
+        run: curl https://raw.githubusercontent.com/Epitech/coding-style-checker/main/coding-style.sh -o /tmp/coding-style.sh; chmod +x /tmp/coding-style.sh
+      - name: Run coding-style.sh
+        run: /tmp/coding-style.sh . .
+      - name: Display banana report
+        run: cat coding-style-reports.log
+      - name: Report banana result
+        run: |
+          NB_ERROR=$(cat coding-style-reports.log | wc -l)
+          if [ $NB_ERROR -gt 0 ]; then
+              ERRORS=$(cat coding-style-reports.log);
+              echo "Banana found $NB_ERROR error(s)"
+              echo "$ERRORS"
+              exit 1
+          fi
+          echo "Everything is good ! Keep on coding !"
+          exit 0
+
   compilation:
     name: Compilation via Makefile
     runs-on: ubuntu-latest
